//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBD.MEDEM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int IdDocumento { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdPuntoCarga { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ClientePuntosCarga ClientePuntosCarga { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual TiposDocumentos TiposDocumentos { get; set; }
    }
}
