//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBD.MEDEM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Clientes = new HashSet<Clientes>();
            this.ComentariosOrigen = new HashSet<ComentariosOrigen>();
            this.Contactos = new HashSet<Contactos>();
        }
    
        public int IdGrupo { get; set; }
        public int IdFase { get; set; }
        public int IdEstatusFases { get; set; }
        public int IdTipoGiro { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> CapacidadKW { get; set; }
        public Nullable<int> PuntosCarga { get; set; }
        public bool Estatus { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosOrigen> ComentariosOrigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contactos> Contactos { get; set; }
        public virtual EstatusFases EstatusFases { get; set; }
        public virtual Fases Fases { get; set; }
        public virtual Grupos Grupos1 { get; set; }
        public virtual Grupos Grupos2 { get; set; }
        public virtual TiposGiros TiposGiros { get; set; }
    }
}
