//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBD.MEDEM.Entities
{
    using System;
    
    public partial class ObtenerGrupos
    {
        public int IdGrupo { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> CapacidadKW { get; set; }
        public bool Estatus { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Fase { get; set; }
        public string EstatusFases { get; set; }
        public Nullable<int> TotalClientes { get; set; }
        public bool EstatusClientes { get; set; }
        public Nullable<int> TotalPuntoCarga { get; set; }
        public bool EstatusPuntoCarga { get; set; }
    }
}
